### ISSUE TITLE
Move example SPARQL queries into separate files for grlc. 

### ISSUE THREAD

**Issue by dougli1sqrd** [cmungall/go-graphstore#16]
Grlc is a service that builds APIs based on sparql files in a repository. 

Let's utilize this by making a new repo in geneontology, moving some example queries in the repo, and then ultimately setting up some grlc to point at rdf.geneontology.org.

This ticket is for creating the repo and moving examples as separate files into the repo.

**Comment by dougli1sqrd** [comment]
https://github.com/geneontology/example-sparql

**Comment by balhoff** [comment]
Looking good - maybe you didn't get to it yet, but I think there is a syntax in grlc for marking variables to be filled in by the API.
