### ISSUE TITLE
consider alternative to downloading bg jar

### ISSUE THREAD

**Issue by cmungall** [cmungall/go-graphstore#3]
@kltm suggests checking in jar, but about mvn/ivy/sbt/gradle instead? http://mvnrepository.com/artifact/com.blazegraph/bigdata-core

**Comment by kltm** [comment]
While better than SF, as this is an embedded application rather than a library for compilation, I'm not sure why you'd want to add an extra build/dl step when having the apparently small jar embedded in the repo is an available alternative?

**Comment by cmungall** [comment]
54M, big enough for github to complain..

**Comment by kltm** [comment]
My bad--when I looked it up, I saw 6.7M...so waaay off.
Absolutely yes, then. My druthers would be maven over the others as my perception is that it is more standard and more likely to be available in whatever environment we find ourselves in. It might be nice to have an "install" target in the Makefile as well.

**Comment by kltm** [comment]
Your link, then to the latest: http://mvnrepository.com/artifact/com.blazegraph/bigdata-core/2.1.4 states 6.7M? Is this just the core lib then, and not the app/runner?
